// mock server data for main page
export const cardsData = [
    {
        id: `${Math.random() * Math.random()}`,
        images: {
            '1x': `${process.env.PUBLIC_URL}/assets/1xblue-nebula-compressed.png`,
            '2x': `${process.env.PUBLIC_URL}/assets/2xblue-nebula-compressed.png`,
            '4x': `${process.env.PUBLIC_URL}/assets/4xblue-nebula.png`,
        },
        title: 'Move the borders of reality',
        caption: 'Go on a space adventure',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget ullamcorper mi. Nam enim odio, laoreet in porta vitae, porttitor in leo. Aenean euismod enim ac semper vehicula. Mauris aliquet vestibulum lectus, et venenatis odio molestie in. Quisque sollicitudin ligula vitae quam porta, ac ornare neque dignissim. Integer massa sem, pulvinar luctus orci sit amet, interdum congue lacus. Aenean eget blandit arcu. Maecenas non bibendum nibh. Phasellus facilisis ipsum id ipsum consequat sollicitudin. Nulla ac faucibus ex.',
    },
    {
        id: `${Math.random() * Math.random()}`,
        images: {
            '1x': `${process.env.PUBLIC_URL}/assets/1xbrown-nebula-compressed.png`,
            '2x': `${process.env.PUBLIC_URL}/assets/2xbrown-nebula-compressed.png`,
            '4x': `${process.env.PUBLIC_URL}/assets/4xbrown-nebula.png`,
        },
        title: 'Space is not just stars and planets',
        caption: 'It is a majestic journey to',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget ullamcorper mi. Nam enim odio, laoreet in porta vitae, porttitor in leo. Aenean euismod enim ac semper vehicula. Mauris aliquet vestibulum lectus, et venenatis odio molestie in. Quisque sollicitudin ligula vitae quam porta, ac ornare neque dignissim. Integer massa sem, pulvinar luctus orci sit amet, interdum congue lacus. Aenean eget blandit arcu. Maecenas non bibendum nibh. Phasellus facilisis ipsum id ipsum consequat sollicitudin. Nulla ac faucibus ex.',
    },
    {
        id: `${Math.random() * Math.random()}`,
        images: {
            '1x': `${process.env.PUBLIC_URL}/assets/1xmilky-way-compressed.png`,
            '2x': `${process.env.PUBLIC_URL}/assets/2xmilky-way-compressed.png`,
            '4x': `${process.env.PUBLIC_URL}/assets/4xmilky-way-compressed.png`,
        },
        title: 'For those who dream of stars',
        caption: 'Our offer: make your dream come true',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget ullamcorper mi. Nam enim odio, laoreet in porta vitae, porttitor in leo. Aenean euismod enim ac semper vehicula. Mauris aliquet vestibulum lectus, et venenatis odio molestie in. Quisque sollicitudin ligula vitae quam porta, ac ornare neque dignissim. Integer massa sem, pulvinar luctus orci sit amet, interdum congue lacus. Aenean eget blandit arcu. Maecenas non bibendum nibh. Phasellus facilisis ipsum id ipsum consequat sollicitudin. Nulla ac faucibus ex.',
    },
    {
        id: `${Math.random() * Math.random()}`,
        images: {
            '1x': `${process.env.PUBLIC_URL}/assets/1xpink-nebula-compressed.png`,
            '2x': `${process.env.PUBLIC_URL}/assets/2xpink-nebula-compressed.png`,
            '4x': `${process.env.PUBLIC_URL}/assets/4xpink-nebula.png`,
        },
        title: 'Fulfill your fantastic dreams',
        caption: 'Space has never been so close',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget ullamcorper mi. Nam enim odio, laoreet in porta vitae, porttitor in leo. Aenean euismod enim ac semper vehicula. Mauris aliquet vestibulum lectus, et venenatis odio molestie in. Quisque sollicitudin ligula vitae quam porta, ac ornare neque dignissim. Integer massa sem, pulvinar luctus orci sit amet, interdum congue lacus. Aenean eget blandit arcu. Maecenas non bibendum nibh. Phasellus facilisis ipsum id ipsum consequat sollicitudin. Nulla ac faucibus ex.',
    },
    {
        id: `${Math.random() * Math.random()}`,
        images: {
            '1x': `${process.env.PUBLIC_URL}/assets/1xblue-nebula-compressed.png`,
            '2x': `${process.env.PUBLIC_URL}/assets/2xblue-nebula-compressed.png`,
            '4x': `${process.env.PUBLIC_URL}/assets/4xblue-nebula.png`,
        },
        title: 'Move the borders of reality',
        caption: 'Go on a space adventure',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget ullamcorper mi. Nam enim odio, laoreet in porta vitae, porttitor in leo. Aenean euismod enim ac semper vehicula. Mauris aliquet vestibulum lectus, et venenatis odio molestie in. Quisque sollicitudin ligula vitae quam porta, ac ornare neque dignissim. Integer massa sem, pulvinar luctus orci sit amet, interdum congue lacus. Aenean eget blandit arcu. Maecenas non bibendum nibh. Phasellus facilisis ipsum id ipsum consequat sollicitudin. Nulla ac faucibus ex.',
    },
    {
        id: `${Math.random() * Math.random()}`,
        images: {
            '1x': `${process.env.PUBLIC_URL}/assets/1xbrown-nebula-compressed.png`,
            '2x': `${process.env.PUBLIC_URL}/assets/2xbrown-nebula-compressed.png`,
            '4x': `${process.env.PUBLIC_URL}/assets/4xbrown-nebula.png`,
        },
        title: 'Space is not just stars and planets',
        caption: 'It is a majestic journey to',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget ullamcorper mi. Nam enim odio, laoreet in porta vitae, porttitor in leo. Aenean euismod enim ac semper vehicula. Mauris aliquet vestibulum lectus, et venenatis odio molestie in. Quisque sollicitudin ligula vitae quam porta, ac ornare neque dignissim. Integer massa sem, pulvinar luctus orci sit amet, interdum congue lacus. Aenean eget blandit arcu. Maecenas non bibendum nibh. Phasellus facilisis ipsum id ipsum consequat sollicitudin. Nulla ac faucibus ex.',
    },
    {
        id: `${Math.random() * Math.random()}`,
        images: {
            '1x': `${process.env.PUBLIC_URL}/assets/1xmilky-way-compressed.png`,
            '2x': `${process.env.PUBLIC_URL}/assets/2xmilky-way-compressed.png`,
            '4x': `${process.env.PUBLIC_URL}/assets/4xmilky-way-compressed.png`,
        },
        title: 'For those who dream of stars',
        caption: 'Our offer: make your dream come true',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget ullamcorper mi. Nam enim odio, laoreet in porta vitae, porttitor in leo. Aenean euismod enim ac semper vehicula. Mauris aliquet vestibulum lectus, et venenatis odio molestie in. Quisque sollicitudin ligula vitae quam porta, ac ornare neque dignissim. Integer massa sem, pulvinar luctus orci sit amet, interdum congue lacus. Aenean eget blandit arcu. Maecenas non bibendum nibh. Phasellus facilisis ipsum id ipsum consequat sollicitudin. Nulla ac faucibus ex.',
    },
    {
        id: `${Math.random() * Math.random()}`,
        images: {
            '1x': `${process.env.PUBLIC_URL}/assets/1xpink-nebula-compressed.png`,
            '2x': `${process.env.PUBLIC_URL}/assets/2xpink-nebula-compressed.png`,
            '4x': `${process.env.PUBLIC_URL}/assets/4xpink-nebula.png`,
        },
        title: 'Fulfill your fantastic dreams',
        caption: 'Space has never been so close',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget ullamcorper mi. Nam enim odio, laoreet in porta vitae, porttitor in leo. Aenean euismod enim ac semper vehicula. Mauris aliquet vestibulum lectus, et venenatis odio molestie in. Quisque sollicitudin ligula vitae quam porta, ac ornare neque dignissim. Integer massa sem, pulvinar luctus orci sit amet, interdum congue lacus. Aenean eget blandit arcu. Maecenas non bibendum nibh. Phasellus facilisis ipsum id ipsum consequat sollicitudin. Nulla ac faucibus ex.',
    },
    {
        id: `${Math.random() * Math.random()}`,
        images: {
            '1x': `${process.env.PUBLIC_URL}/assets/1xblue-nebula-compressed.png`,
            '2x': `${process.env.PUBLIC_URL}/assets/2xblue-nebula-compressed.png`,
            '4x': `${process.env.PUBLIC_URL}/assets/4xblue-nebula.png`,
        },
        title: 'Move the borders of reality',
        caption: 'Go on a space adventure',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget ullamcorper mi. Nam enim odio, laoreet in porta vitae, porttitor in leo. Aenean euismod enim ac semper vehicula. Mauris aliquet vestibulum lectus, et venenatis odio molestie in. Quisque sollicitudin ligula vitae quam porta, ac ornare neque dignissim. Integer massa sem, pulvinar luctus orci sit amet, interdum congue lacus. Aenean eget blandit arcu. Maecenas non bibendum nibh. Phasellus facilisis ipsum id ipsum consequat sollicitudin. Nulla ac faucibus ex.',
    },
    {
        id: `${Math.random() * Math.random()}`,
        images: {
            '1x': `${process.env.PUBLIC_URL}/assets/1xbrown-nebula-compressed.png`,
            '2x': `${process.env.PUBLIC_URL}/assets/2xbrown-nebula-compressed.png`,
            '4x': `${process.env.PUBLIC_URL}/assets/4xbrown-nebula.png`,
        },
        title: 'Space is not just stars and planets',
        caption: 'It is a majestic journey to',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget ullamcorper mi. Nam enim odio, laoreet in porta vitae, porttitor in leo. Aenean euismod enim ac semper vehicula. Mauris aliquet vestibulum lectus, et venenatis odio molestie in. Quisque sollicitudin ligula vitae quam porta, ac ornare neque dignissim. Integer massa sem, pulvinar luctus orci sit amet, interdum congue lacus. Aenean eget blandit arcu. Maecenas non bibendum nibh. Phasellus facilisis ipsum id ipsum consequat sollicitudin. Nulla ac faucibus ex.',
    },
    {
        id: `${Math.random() * Math.random()}`,
        images: {
            '1x': `${process.env.PUBLIC_URL}/assets/1xblue-nebula-compressed.png`,
            '2x': `${process.env.PUBLIC_URL}/assets/2xblue-nebula-compressed.png`,
            '4x': `${process.env.PUBLIC_URL}/assets/4xblue-nebula.png`,
        },
        title: 'Move the borders of reality',
        caption: 'Go on a space adventure',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget ullamcorper mi. Nam enim odio, laoreet in porta vitae, porttitor in leo. Aenean euismod enim ac semper vehicula. Mauris aliquet vestibulum lectus, et venenatis odio molestie in. Quisque sollicitudin ligula vitae quam porta, ac ornare neque dignissim. Integer massa sem, pulvinar luctus orci sit amet, interdum congue lacus. Aenean eget blandit arcu. Maecenas non bibendum nibh. Phasellus facilisis ipsum id ipsum consequat sollicitudin. Nulla ac faucibus ex.',
    },
    {
        id: `${Math.random() * Math.random()}`,
        images: {
            '1x': `${process.env.PUBLIC_URL}/assets/1xbrown-nebula-compressed.png`,
            '2x': `${process.env.PUBLIC_URL}/assets/2xbrown-nebula-compressed.png`,
            '4x': `${process.env.PUBLIC_URL}/assets/4xbrown-nebula.png`,
        },
        title: 'Space is not just stars and planets',
        caption: 'It is a majestic journey to',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget ullamcorper mi. Nam enim odio, laoreet in porta vitae, porttitor in leo. Aenean euismod enim ac semper vehicula. Mauris aliquet vestibulum lectus, et venenatis odio molestie in. Quisque sollicitudin ligula vitae quam porta, ac ornare neque dignissim. Integer massa sem, pulvinar luctus orci sit amet, interdum congue lacus. Aenean eget blandit arcu. Maecenas non bibendum nibh. Phasellus facilisis ipsum id ipsum consequat sollicitudin. Nulla ac faucibus ex.',
    },
    {
        id: `${Math.random() * Math.random()}`,
        images: {
            '1x': `${process.env.PUBLIC_URL}/assets/1xmilky-way-compressed.png`,
            '2x': `${process.env.PUBLIC_URL}/assets/2xmilky-way-compressed.png`,
            '4x': `${process.env.PUBLIC_URL}/assets/4xmilky-way-compressed.png`,
        },
        title: 'For those who dream of stars',
        caption: 'Our offer: make your dream come true',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget ullamcorper mi. Nam enim odio, laoreet in porta vitae, porttitor in leo. Aenean euismod enim ac semper vehicula. Mauris aliquet vestibulum lectus, et venenatis odio molestie in. Quisque sollicitudin ligula vitae quam porta, ac ornare neque dignissim. Integer massa sem, pulvinar luctus orci sit amet, interdum congue lacus. Aenean eget blandit arcu. Maecenas non bibendum nibh. Phasellus facilisis ipsum id ipsum consequat sollicitudin. Nulla ac faucibus ex.',
    },
    {
        id: `${Math.random() * Math.random()}`,
        images: {
            '1x': `${process.env.PUBLIC_URL}/assets/1xpink-nebula-compressed.png`,
            '2x': `${process.env.PUBLIC_URL}/assets/2xpink-nebula-compressed.png`,
            '4x': `${process.env.PUBLIC_URL}/assets/4xpink-nebula.png`,
        },
        title: 'Fulfill your fantastic dreams',
        caption: 'Space has never been so close',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget ullamcorper mi. Nam enim odio, laoreet in porta vitae, porttitor in leo. Aenean euismod enim ac semper vehicula. Mauris aliquet vestibulum lectus, et venenatis odio molestie in. Quisque sollicitudin ligula vitae quam porta, ac ornare neque dignissim. Integer massa sem, pulvinar luctus orci sit amet, interdum congue lacus. Aenean eget blandit arcu. Maecenas non bibendum nibh. Phasellus facilisis ipsum id ipsum consequat sollicitudin. Nulla ac faucibus ex.',
    },
    {
        id: `${Math.random() * Math.random()}`,
        images: {
            '1x': `${process.env.PUBLIC_URL}/assets/1xblue-nebula-compressed.png`,
            '2x': `${process.env.PUBLIC_URL}/assets/2xblue-nebula-compressed.png`,
            '4x': `${process.env.PUBLIC_URL}/assets/4xblue-nebula.png`,
        },
        title: 'Move the borders of reality',
        caption: 'Go on a space adventure',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget ullamcorper mi. Nam enim odio, laoreet in porta vitae, porttitor in leo. Aenean euismod enim ac semper vehicula. Mauris aliquet vestibulum lectus, et venenatis odio molestie in. Quisque sollicitudin ligula vitae quam porta, ac ornare neque dignissim. Integer massa sem, pulvinar luctus orci sit amet, interdum congue lacus. Aenean eget blandit arcu. Maecenas non bibendum nibh. Phasellus facilisis ipsum id ipsum consequat sollicitudin. Nulla ac faucibus ex.',
    },
    {
        id: `${Math.random() * Math.random()}`,
        images: {
            '1x': `${process.env.PUBLIC_URL}/assets/1xbrown-nebula-compressed.png`,
            '2x': `${process.env.PUBLIC_URL}/assets/2xbrown-nebula-compressed.png`,
            '4x': `${process.env.PUBLIC_URL}/assets/4xbrown-nebula.png`,
        },
        title: 'Space is not just stars and planets',
        caption: 'It is a majestic journey to',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget ullamcorper mi. Nam enim odio, laoreet in porta vitae, porttitor in leo. Aenean euismod enim ac semper vehicula. Mauris aliquet vestibulum lectus, et venenatis odio molestie in. Quisque sollicitudin ligula vitae quam porta, ac ornare neque dignissim. Integer massa sem, pulvinar luctus orci sit amet, interdum congue lacus. Aenean eget blandit arcu. Maecenas non bibendum nibh. Phasellus facilisis ipsum id ipsum consequat sollicitudin. Nulla ac faucibus ex.',
    },
    {
        id: `${Math.random() * Math.random()}`,
        images: {
            '1x': `${process.env.PUBLIC_URL}/assets/1xmilky-way-compressed.png`,
            '2x': `${process.env.PUBLIC_URL}/assets/2xmilky-way-compressed.png`,
            '4x': `${process.env.PUBLIC_URL}/assets/4xmilky-way-compressed.png`,
        },
        title: 'For those who dream of stars',
        caption: 'Our offer: make your dream come true',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget ullamcorper mi. Nam enim odio, laoreet in porta vitae, porttitor in leo. Aenean euismod enim ac semper vehicula. Mauris aliquet vestibulum lectus, et venenatis odio molestie in. Quisque sollicitudin ligula vitae quam porta, ac ornare neque dignissim. Integer massa sem, pulvinar luctus orci sit amet, interdum congue lacus. Aenean eget blandit arcu. Maecenas non bibendum nibh. Phasellus facilisis ipsum id ipsum consequat sollicitudin. Nulla ac faucibus ex.',
    },
    {
        id: `${Math.random() * Math.random()}`,
        images: {
            '1x': `${process.env.PUBLIC_URL}/assets/1xpink-nebula-compressed.png`,
            '2x': `${process.env.PUBLIC_URL}/assets/2xpink-nebula-compressed.png`,
            '4x': `${process.env.PUBLIC_URL}/assets/4xpink-nebula.png`,
        },
        title: 'Fulfill your fantastic dreams',
        caption: 'Space has never been so close',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget ullamcorper mi. Nam enim odio, laoreet in porta vitae, porttitor in leo. Aenean euismod enim ac semper vehicula. Mauris aliquet vestibulum lectus, et venenatis odio molestie in. Quisque sollicitudin ligula vitae quam porta, ac ornare neque dignissim. Integer massa sem, pulvinar luctus orci sit amet, interdum congue lacus. Aenean eget blandit arcu. Maecenas non bibendum nibh. Phasellus facilisis ipsum id ipsum consequat sollicitudin. Nulla ac faucibus ex.',
    },
    {
        id: `${Math.random() * Math.random()}`,
        images: {
            '1x': `${process.env.PUBLIC_URL}/assets/1xblue-nebula-compressed.png`,
            '2x': `${process.env.PUBLIC_URL}/assets/2xblue-nebula-compressed.png`,
            '4x': `${process.env.PUBLIC_URL}/assets/4xblue-nebula.png`,
        },
        title: 'Move the borders of reality',
        caption: 'Go on a space adventure',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget ullamcorper mi. Nam enim odio, laoreet in porta vitae, porttitor in leo. Aenean euismod enim ac semper vehicula. Mauris aliquet vestibulum lectus, et venenatis odio molestie in. Quisque sollicitudin ligula vitae quam porta, ac ornare neque dignissim. Integer massa sem, pulvinar luctus orci sit amet, interdum congue lacus. Aenean eget blandit arcu. Maecenas non bibendum nibh. Phasellus facilisis ipsum id ipsum consequat sollicitudin. Nulla ac faucibus ex.',
    },
    {
        id: `${Math.random() * Math.random()}`,
        images: {
            '1x': `${process.env.PUBLIC_URL}/assets/1xbrown-nebula-compressed.png`,
            '2x': `${process.env.PUBLIC_URL}/assets/2xbrown-nebula-compressed.png`,
            '4x': `${process.env.PUBLIC_URL}/assets/4xbrown-nebula.png`,
        },
        title: 'Space is not just stars and planets',
        caption: 'It is a majestic journey to',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget ullamcorper mi. Nam enim odio, laoreet in porta vitae, porttitor in leo. Aenean euismod enim ac semper vehicula. Mauris aliquet vestibulum lectus, et venenatis odio molestie in. Quisque sollicitudin ligula vitae quam porta, ac ornare neque dignissim. Integer massa sem, pulvinar luctus orci sit amet, interdum congue lacus. Aenean eget blandit arcu. Maecenas non bibendum nibh. Phasellus facilisis ipsum id ipsum consequat sollicitudin. Nulla ac faucibus ex.',
    },
];
